src/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', views.band_list, name='band-list'),
    path('bands/<int:band_id>/', views.band_detail, name="band-detail"),
    path('bands/add/', views.band_create, name="band-create"),
    path('hello/', views.band_list),
    path('about-us/', views.about),
    path('listings/', views.listings_list, name="listings-list"),
    path('listings/<int:listing_id>/', views.listings_detail, name="listings-detail"),
    path('contact/', views.contact, name='contact'),]

src/listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

class Band(models.Model):

    def __str__(self):
        return f'{self.name}' #Nom du groupe
    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'
    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(default='AR', choices=Genre.choices, max_length=10)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(default=2000,
    validators=[MinValueValidator(1900), MaxValueValidator(2021)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)

class Listing(models.Model):
    name = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=500)
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(validators=[MaxValueValidator(2024), MinValueValidator(1900)])
    class Type(models.TextChoices):
        RECORDS = "disques"
        CLOTHING = "vetements"
        POSTERS = "affiches"
        MISCELLANEOUS = "divers"
    type = models.fields.CharField(choices=Type.choices, max_length=10)
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

src/listings/forms.py
from django import forms
from listings.models import Band

class ContactUsForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=100)

class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        fields = "__all__"

src/listings/views.py
from django.http import HttpResponse
from django.shortcuts import render
from listings.models import Band
from listings.models import Listing
from listings.forms import BandForm, ContactUsForm
from django.core.mail import send_mail
from django.shortcuts import redirect

# listings/views.pys

def band_list(request):  # renommer la fonction de vue
   bands = Band.objects.all()
   return render(request,
           'listings/band_list.html',  # pointe vers le nouveau nom de modèle
           {'bands': bands})

def about(request):
    listings = Listing.objects.all()
    return render(request, 'listings/about.html', {'listings': listings})

def contact(request):
    print("requete :", request.method)
    print("post :", request.POST)
    if request.method == "POST":
        form = ContactUsForm(request.POST)
        if form.is_valid():
            send_mail(
            subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us form',
            message=form.cleaned_data['message'],
            from_email=form.cleaned_data['email'],
            recipient_list=['admin@merchex.xyz'],
        )
    else:
        form = ContactUsForm()
    return render(request, 'listings/contact.html', {"form":form})

def band_detail(request, band_id):
    band = Band.objects.get(id=band_id)
    return render(request, 'listings/band_detail.html', {'band': band})

def listings_detail(request, listing_id):
    listing = Listing.objects.get(id=listing_id)
    return render(request, 'listings/listings_detail.html', {'listing': listing})

def listings_list(request):
    listings = Listing.objects.all()
    return render(request, 'listings/listings_list.html', {'listings': listings})

def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)
        if form.is_valid():
            band = form.save()
            return redirect('band-detail', band.id)
    else:
        form = BandForm()
    return render(request, 'listings/band_create.html', {'form':form})

src/listings/templates/listings/about.html
{% extends "listings/base.html" %}

{% block content %}

<h1>Ta soeur en slibar</h1>
<ul>
    {% for band in bands%}
    <li>{{band.name}}</li>
    {% endfor %}
</ul>

{% endblock %}

src/listings/templates/listings/band_create.html
{% extends "listings/base.html"%}

{% block content %}

<h1>Créer un nouveau groupe</h1>

<form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>

{% endblock %}

src/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}

<h2>{{ band.name }}</h2>

<ul>
 <li>Genre : {{ band.get_genre_display }}</li>
 <li>Année de formation : {{ band.year_formed }}</li>
 <li>Actif : {{ band.active| yesno }}</li>
 {% if band.official_homepage %}
 <li><a href="{{ band.official_homepage }}">{{band.official_homepage}}</a></li>
 {%endif%}
<a href="{% url 'band-list' %}">Retour à tous les groupes</a>
</ul>

<p>{{ band.biography }}</p>

{% endblock %}

src/listings/templates/listings/band_list.html
{% extends "listings/base.html" %}

{% block content %}
<h1>Liste des groupes</h1>
<a href="{% url 'band-create' %}">Créer un nouveau groupe</a>
<ul>
    {% for band in bands %}
        <li><a href="{% url 'band-detail' band.id %}">{{ band.name }}</a></li>
    {% endfor %}
</ul>

{% endblock %}

src/listings/templates/listings/base.html
{% load static %}
<html>
    <head>
        <title>FT_PROUT</title>
        <link rel="stylesheet" href="{% static "listings/style.css" %}" />
    </head>
    <body>

        {% block content %}{% endblock %}

    </body>
</html>

src/listings/templates/listings/contact.html
{% extends "listings/base.html" %}

{% block content %}

<p>Nous sommes là pour vous aider.</p>

<form action="" method="post" novalidate>
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Envoyer">
</form>

{% endblock %}

src/listings/templates/listings/listings_detail.html
{% extends "listings/base.html" %}

{% block content %}

<h2>{{ listing.name }}</h2>

<ul>
    <li>Description : {{ listing.description }}</li>
    <li>Sold : {{ listing.sold| yesno }}</li>
    <li>Year : {{ listing.year }}</li>
    <li>Type : {{ listing.get_type_display }}</li>
    <li>Band : {{ listing.band }}</li>
    <a href="{% url 'listings-list' %}">Retour à tous les groupes</a>
</ul>

{% endblock %}

src/listings/templates/listings/listings_list.html
{% extends "listings/base.html" %}

{% block content %}

<ul>
    {% for listing in listings %}
    <li><a href="{% url 'listings-detail' listing.id %}">{{ listing.name }}</a></li>
    {% endfor %}
</ul>

{% endblock %}